window.DsRemark={
	global:{
		//数据源名称
		dsName:'数据源名称长度不能超过100,且不能出现重复的数据源名称。',
		//连接用户
		connUser:'连接用户的长度不能超过100，且不能为中文，不能为空。',
		//连接密码
		connPwd:'连接密码的长度不能超过100，且不能为中文，不能为空。',
		//连接URL
		connUrl:'连接URL的按照格式严格输入，server改为IP地址，默认oracle端口为1521,可根据具体情况修改,dbname改为数据库名。且不能为空。',
		//描述
		remark:'输入对数据源的描述。',
		//连接驱动
		driverSelect:'选择连接驱动为DB2或者Oracle等等。'
	}
};